name: Sync README

on:
  push:
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          repository: cognitive-metascience/.github
          ref: main          
          path: .github-repo

      - name: Check if destination repo exists
        id: check_repo
        run: |
          if gh repo view cognitive-metascience/cognitive-metascience.github.io &>/dev/null; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout destination
        uses: actions/checkout@v3
        with:
          repository: cognitive-metascience/cognitive-metascience.github.io          
          token: ${{ secrets.PAT_TOKEN }}
          ref: main
          path: github-io-repo

      - name: Copy README to docs directory
        run: |
          mkdir -p github-io-repo/docs
          cp .github-repo/README.md github-io-repo/docs/README.md

      - name: Commit and push changes to cognitive-metascience.github.io
        run: |
          cd github-io-repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/README.md
          git commit -m "Sync README to docs directory" || echo "No changes to commit"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/cognitive-metascience/cognitive-metascience.github.io HEAD:main

      - name: Update profile README in .github repository
        run: |
          cd .github-repo
          mkdir -p profile
          cp README.md profile/README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile/README.md
          git commit -m "Update profile README" || echo "No changes to commit"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/cognitive-metascience/.github HEAD:main
