name: Sync README

on:
  push:
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          repository: cognitive-metascience/.github
          ref: main
          path: source

      - name: Check if destination repo exists
        id: check_repo
        run: |
          if gh repo view cognitive-metascience/cognitive-metascience.github.io &>/dev/null; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create destination repo if it doesn't exist
        if: steps.check_repo.outputs.exists == 'false'
        run: |
          gh repo create cognitive-metascience/cognitive-metascience.github.io --public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout destination
        uses: actions/checkout@v3
        with:
          repository: cognitive-metascience/cognitive-metascience.github.io
          path: destination

      - name: Copy README to destination root
        run: |
          cp source/README.md destination/README.md

      - name: Create profile directory and copy README
        run: |
          mkdir -p source/profile
          cp source/README.md source/profile/README.md

      - name: Commit changes to destination
        run: |
          cd destination
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Sync README from .github repository" || echo "No changes to commit"
          git push

      - name: Commit changes to source
        run: |
          cd source
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile/README.md
          git commit -m "Copy README to profile directory" || echo "No changes to commit"
          git push
